export const EXAMPLE_SEQUENCES = {
  enzyme: {
    label: 'Enzyme Target',
    description: 'Human CDK2 — a key cell cycle kinase',
    sequence: `MENFQKVEKIGEGTYGVVYKARNKLTGEVVALKKIRLDTETEGVPSTAIREISLLKELNHPNIVKLLDVIHTENKLYLVFEFLHQDLKKFMDASALTGIPLPLIKSYLFQLLQGLAFCHSHRVLHRDLKPQNLLINTEGAIKLADFGLARAFGVPVRTYTHEVVTLWYRAPEILLGSKYYSTPVDIWSVGCIFAEMVTRRALFPGDSEIDQLFRIFRTLGTPDEVVWPGVTSMPDYKPSFPKWARQDFSKVVPPLDEDGRSLLSQMLHYDPNKRISAKAALAHPFFQDVTKPVPHLRL`,
  },
  ionChannel: {
    Label: 'Ion Channel',
    description: 'Human KCNA1 — voltage-gated potassium channel',
    sequence: `MAAAGAGAGPRPAGARGARRAAAAAAGAAAGAAAGAAARAAGAGEGRGAAGGGGCGAAAAGDSGDGKGGKKKGKKKGKGKKKGGKGKAAAKDKKKDKDKKDGDAEPPGDAEHSATPLSTIPLSKKDSISKPSTLNSTKLPEPKEGPHLRPATAIQSLIQTFMQHHLASQRAVCMRESDPLLSAGEAKIYYPQTKLGQVKKLKKLSSQPKPPVTQNQVTQSLEQQLQALQARIREQER`,
  },
  transporter: {
    label: 'Transport Worker',
    description: 'Human SLC2A1 — GLUT1 glucose transporter',
    sequence: `MEPSSKKLTGRLMLAVGGAVLGSLQFGYNTGVINAPQKVIEEFYNQTWVHRYGESIPQDLGKPQRSPGLLSSALTVIALMFFSMLILGFSKLPETKGRTFDEIASGFRQGGASIKGALVPALLAGLCASLATFFLSYLFGKINDTVLDKPETERKIVQELKDAGKIRAMVCNSAVPSFLHSICSSSPYQDREERQMRQHLANGTSSQPASPVSEGTSRSQYQPLPQPQPQSYRTQSS`,
  },
}